name: R Package Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: Test - ${{ matrix.config.os }} (R ${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: 'ubuntu-latest', r: '4.3'}
          - {os: 'macos-latest', r: '4.3'}
          - {os: 'windows-latest', r: '4.3'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::testthat
            any::Rcpp
            any::RcppArmadillo
            any::RcppProgress
            any::BH
            any::foreach
            any::doParallel
            any::knitr
            any::rmarkdown

      - name: Install package
        run: |
          devtools::install(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run tests
        run: |
          testthat::test_package("sglOptim")
        shell: Rscript {0}
