name: Build Vignettes

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build-vignettes:
    runs-on: ubuntu-latest
    name: Build Vignettes

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::Rcpp
            any::RcppArmadillo
            any::RcppProgress
            any::BH
            any::foreach
            any::doParallel
            any::knitr
            any::rmarkdown

      - name: Build vignettes
        run: |
          devtools::install(dependencies = TRUE)
          devtools::build_vignettes()
        shell: Rscript {0}
